[package]
name = "z-proxmon"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

triomphe = "0.1"
blake3 = "1.8"

compio = { version = "0.19", features = ["fs", "process"] }
futures-util = "0.3"

axum = { version = "0.8", default-features = false, features = ["http1", "http2", "json", "query"] }
cyper-axum = { version = "0.9", features = ["http2"] }

sysinfo = { version = "0.39", features = ["serde"] }
nvml-wrapper = "0.12"

z-sync = { git = "https://github.com/imzacm/z-sync.git", rev = "934a8d4473b3f6843a248ef6b11d0589318adc8b", features = ["triomphe-arc"] }
z-queue = { git = "https://github.com/imzacm/z-queue.git", rev = "039e9e9cb22244049f31feee999d7004ce551493", features = ["triomphe", "stream"] }

lru = "0.18"
tempfile = "3.27"
time = { version = "0.3", features = ["serde", "serde-well-known"] }
bincode = { version = "2.0.1", features = ["serde"] }

tokio = { version = "1", default-features = false, features = ["rt", "parking_lot"] }
tapo = "0.9"
